# Generated by Django 3.0.5 on 2020-04-23 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200423_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 13, 17, 31, 135078, tzinfo=utc)),
        ),
    ]
